version: "3.9"
services:
  chatgpt_react_flask_app:
    container_name: chatgpt_react_flask_app
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ./:/usr/src/app
  chatgpt_react_flask_redis:
    container_name: chatgpt_react_flask_redis 
    image: redis 
    ports:
      - "6380:6379"
